import mongoose, { Schema, Document } from 'mongoose';

/**
 * Exercise interface representing a single exercise within a workout
 */
export interface IExercise {
  name: string;         // Name of the exercise (e.g., "Bench Press")
  sets: number;         // Number of sets performed
  reps: number;         // Number of repetitions per set
  weight?: number;      // Weight used (if applicable)
  duration?: number;    // Duration in seconds (if applicable)
  calories?: number;    // Estimated calories burned
  notes?: string;        // Optional notes about the exercise
  formFeedback?: string[]; // Feedback from AI form analysis (if available)
  formScore?: number;   // Score from 0-10 for form quality (if available)
}

/**
 * Exercise as a document interface
 */
export interface IExerciseDocument extends IExercise, Document {}

/**
 * Workout interface representing a complete workout session
 */
export interface IWorkout extends Document {
  user: mongoose.Types.ObjectId;
  name: string;          // Name of the workout (e.g., "Monday Upper Body")
  type: string;          // Type of workout (e.g., "Strength", "Cardio")
  date: Date;            // Date the workout was performed
  duration?: number;     // Total duration in seconds
  totalCalories?: number; // Total calories burned (if tracked)
  exercises: IExerciseDocument[]; // Array of exercises included in the workout
  notes?: string;        // Optional notes about the workout
  completed: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * WorkoutCreateDto - Data transfer object for creating a new workout
 * (Omitting fields that should be generated by the server)
 */
export type WorkoutCreateDto = Omit<IWorkout, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * WorkoutUpdateDto - Data transfer object for updating an existing workout
 */
export type WorkoutUpdateDto = Partial<Omit<IWorkout, 'id' | 'userId' | 'createdAt' | 'updatedAt'>>;

/**
 * Response object for returning workout(s) to the client
 */
export interface WorkoutResponse {
  id: string;
  userId: string;
  name: string;
  type: string;
  exercises: IExercise[];
  date: string;
  notes?: string;
  totalCalories?: number;
  duration?: number;
  createdAt: string;
  updatedAt: string;
}

// Exercise schema
const ExerciseSchema = new Schema<IExerciseDocument>({
  name: {
    type: String,
    required: [true, 'Exercise name is required']
  },
  sets: {
    type: Number,
    required: [true, 'Number of sets is required'],
    min: [1, 'Must have at least 1 set']
  },
  reps: {
    type: Number,
    required: [true, 'Number of reps is required'],
    min: [1, 'Must have at least 1 rep']
  },
  weight: {
    type: Number,
    min: [0, 'Weight cannot be negative']
  },
  duration: {
    type: Number,
    min: [0, 'Duration cannot be negative']
  },
  calories: { type: Number },
  notes: String,
  formFeedback: [String],
  formScore: { type: Number }
});

// Workout schema
const WorkoutSchema = new Schema<IWorkout>(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    name: {
      type: String,
      required: [true, 'Workout name is required'],
      trim: true
    },
    type: {
      type: String,
      required: [true, 'Workout type is required'],
      enum: ['strength', 'cardio', 'flexibility', 'hiit', 'other']
    },
    date: { type: Date, default: Date.now, index: true },
    duration: {
      type: Number,
      min: [0, 'Duration cannot be negative']
    },
    totalCalories: { type: Number },
    exercises: {
      type: [ExerciseSchema],
      required: [true, 'Exercises are required'],
      validate: {
        validator: function(exercises: IExercise[]) {
          return exercises.length > 0;
        },
        message: 'Workout must have at least one exercise'
      }
    },
    notes: { type: String },
    completed: {
      type: Boolean,
      default: false
    }
  },
  { timestamps: true }
);

// Create and export the model
export default mongoose.model<IWorkout>('Workout', WorkoutSchema); 